export const USER_ROLES = {
  LEARNER: 'learner',
  ADMIN: 'admin',
  INSTITUTE: 'institute',
  EMPLOYER: 'employer',
} as const

export const STORAGE_KEYS = {
  ACCESS_TOKEN: 'accessToken',
  REFRESH_TOKEN: 'refreshToken',
  USER: 'user',
} as const

export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  VERIFY_EMAIL: '/verify-email',
  
  LEARNER_DASHBOARD: '/learner/dashboard',
  LEARNER_PROFILE: '/learner/profile',
  LEARNER_CREDENTIALS: '/learner/credentials',
  LEARNER_ADD_CREDENTIAL: '/learner/credentials/add',
  LEARNER_PATHWAYS: '/learner/pathways',
  LEARNER_MY_PATHWAY: '/learner/my-pathway',
  
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_USERS: '/admin/users',
  ADMIN_INSTITUTES: '/admin/institutes',
  ADMIN_PENDING_INSTITUTES: '/admin/institutes/pending',
  ADMIN_CREDENTIALS: '/admin/credentials',
  ADMIN_PATHWAYS: '/admin/pathways',
  ADMIN_SECURITY: '/admin/security',
  ADMIN_LEARNERS: '/admin/learners',
  ADMIN_EMPLOYERS: '/admin/employers',
  ADMIN_EMPLOYER_DETAILS: (id: string) => `/admin/employers/${id}`,
  ADMIN_EMPLOYER_ACTIVITY: (id: string) => `/admin/employers/${id}/activity`,
  ADMIN_EMPLOYER_VERIFICATIONS: (id: string) => `/admin/employers/${id}/verifications`,
  ADMIN_DASHBOARD_ANALYTICS: '/admin/dashboard/analytics',
  
  INSTITUTE_DASHBOARD: '/institute/dashboard',
  INSTITUTE_CREDENTIALS: '/institute/credentials',
  INSTITUTE_PENDING_CREDENTIALS: '/institute/credentials/pending',
  INSTITUTE_VERIFIED_CREDENTIALS: '/institute/credentials/verified',
  INSTITUTE_LEARNERS: '/institute/learners',
  INSTITUTE_SETTINGS: '/institute/settings',
  
  EMPLOYER_DASHBOARD: '/employer/dashboard',
} as const

export const API_ENDPOINTS = {
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  LOGOUT: '/auth/logout',
  VERIFY_EMAIL: '/auth/verify-email',
  RESEND_OTP: '/auth/resend-otp',
  FORGOT_PASSWORD: '/auth/forgot-password',
  RESET_PASSWORD: '/auth/reset-password',
  REFRESH_TOKEN: '/auth/refresh-token',
  
  GET_PROFILE: '/users/profile',
  UPDATE_PROFILE: '/users/profile',
  CHANGE_PASSWORD: '/users/change-password',
  
  UPLOAD_SINGLE: '/upload/single',
  UPLOAD_IMAGE: '/upload/image',
  UPLOAD_PDF: '/upload/pdf',
  UPLOAD_CERTIFICATE: '/upload/certificate',
  
  LEARNER_PROFILE: '/learner/profile',
  LEARNER_DASHBOARD: '/learner/dashboard',
  LEARNER_CREDENTIALS: '/learner/credentials',
  LEARNER_UPLOAD_CREDENTIAL: '/learner/upload-credential',
  LEARNER_PATHWAYS: '/learner/pathways',
  LEARNER_ENROLL_PATHWAY: '/learner/enroll-pathway',
  LEARNER_ENROLLMENTS: '/learner/enrollments',
  LEARNER_MY_PATHWAY: '/learner/my-pathway',
  LEARNER_UNENROLL_PATHWAY: (pathwayId: string) => `/learner/enrollments/${pathwayId}`,
  LEARNER_INSTITUTIONS: '/learner/institutions',
  LEARNER_INSTITUTIONS_SEARCH: '/learner/institutions/search',
  LEARNER_JOIN_INSTITUTE: '/learner/join-institute',
  
  ADMIN_DASHBOARD: '/admin/dashboard',
  GET_ALL_INSTITUTES: '/admin/institutes',
  GET_PENDING_INSTITUTES: '/admin/institutes/pending',
  GET_INSTITUTE_BY_ID: (id: string) => `/admin/institutes/${id}`,
  UPDATE_INSTITUTE: (id: string) => `/admin/institutes/${id}`,
  DELETE_INSTITUTE: (id: string) => `/admin/institutes/${id}`,
  APPROVE_INSTITUTE: (id: string) => `/admin/institutes/${id}/approve`,
  REJECT_INSTITUTE: (id: string) => `/admin/institutes/${id}/reject`,
  GET_ALL_USERS: '/admin/users',
  DEACTIVATE_USER: (id: string) => `/admin/users/${id}/deactivate`,
  
  GET_ALL_EMPLOYERS: '/admin/employers',
  GET_EMPLOYER_ANALYTICS: '/admin/employers/analytics',
  GET_EMPLOYER_BY_ID: (id: string) => `/admin/employers/${id}`,
  GET_EMPLOYER_ACTIVITY: (id: string) => `/admin/employers/${id}/activity`,
  GET_EMPLOYER_VERIFICATIONS: (id: string) => `/admin/employers/${id}/verifications`,
  APPROVE_EMPLOYER: (id: string) => `/admin/employers/${id}/approve`,
  SUSPEND_EMPLOYER: (id: string) => `/admin/employers/${id}/suspend`,
  DEACTIVATE_EMPLOYER: (id: string) => `/admin/employers/${id}/deactivate`,
  DELETE_EMPLOYER: (id: string) => `/admin/employers/${id}`,
  
  INSTITUTE_DASHBOARD: '/institute/dashboard',
  INSTITUTE_CREDENTIALS: '/institute/credentials',
  INSTITUTE_PENDING_CREDENTIALS: '/institute/credentials/pending',
  INSTITUTE_LEARNERS: '/institute/learners',
  INSTITUTE_VERIFY_CREDENTIAL: (id: string) => `/institute/credentials/${id}/verify`,
  INSTITUTE_REJECT_CREDENTIAL: (id: string) => `/institute/credentials/${id}/reject`,
} as const
